<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net5.0</TargetFramework>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
        <IntermediateOutputPath>obj\Debug\net5.0</IntermediateOutputPath>
        <IntermediateOutputPath>obj\Debug\net5.0</IntermediateOutputPath>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\CRM.DataProviders\CRM.DataProviders.csproj" />
    </ItemGroup>
    <ItemGroup>
        <Folder Include="Exceptions\" />
    </ItemGroup>
</Project>