<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Common\" />
    <Folder Include="Aggregates\" />
    <Folder Include="SeedWork\" />
    <Folder Include="Aggregates\CustomerAggregate\" />
    <Folder Include="Events\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MediatR" Version="9.0.0" />
    <PackageReference Include="FluentValidation" Version="10.3.4" />
  </ItemGroup>
</Project>
