<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Commands\" />
    <Folder Include="CommandHandlers\" />
    <Folder Include="IntegrationEvents\" />
    <Folder Include="IntegrationEvents\Events\" />
    <Folder Include="IntegrationEvents\EventHandlers\" />
    <Folder Include="Validations\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MediatR" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="5.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CustomerManagement.Domain\CustomerManagement.Domain.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\EventBus\EventBus\EventBus.csproj" />
    <ProjectReference Include="..\CustomerManagement.Infrastructure\CustomerManagement.Infrastructure.csproj" />
  </ItemGroup>
</Project>
