// <auto-generated />
using System;
using CustomerManagement.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CustomerManagement.Infrastructure.Migrations
{
    [DbContext(typeof(CustomerManagementContext))]
    [Migration("20211110213132_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CustomerManagement.Domain.Aggregates.CustomerAggregate.AddressType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.ToTable("AddressTypes", "CustomerManagement");
                });

            modelBuilder.Entity("CustomerManagement.Domain.Aggregates.CustomerAggregate.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("GenderId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("EmailAddress")
                        .IsUnique();

                    b.HasIndex("GenderId");

                    b.ToTable("Customers", "CustomerManagement");
                });

            modelBuilder.Entity("CustomerManagement.Domain.Aggregates.CustomerAggregate.Gender", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.ToTable("Genders", "CustomerManagement");
                });

            modelBuilder.Entity("CustomerManagement.Domain.Aggregates.CustomerAggregate.TelephoneType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.ToTable("TelephoneTypes", "CustomerManagement");
                });

            modelBuilder.Entity("CustomerManagement.Domain.Aggregates.CustomerAggregate.Customer", b =>
                {
                    b.HasOne("CustomerManagement.Domain.Aggregates.CustomerAggregate.Gender", "Gender")
                        .WithMany("Customers")
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("CustomerManagement.Domain.Aggregates.CustomerAggregate.Address", "Addresses", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("AddressTypeId")
                                .HasColumnType("int")
                                .HasColumnName("AddressTypeId");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)");

                            b1.Property<string>("CountryISO3")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("nvarchar(16)");

                            b1.Property<string>("StreetName")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)");

                            b1.Property<string>("StreetNumber")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("nvarchar(16)");

                            b1.HasKey("CustomerId", "Id");

                            b1.HasIndex("AddressTypeId");

                            b1.ToTable("Address");

                            b1.HasOne("CustomerManagement.Domain.Aggregates.CustomerAggregate.AddressType", "AddressType")
                                .WithMany()
                                .HasForeignKey("AddressTypeId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");

                            b1.Navigation("AddressType");
                        });

                    b.OwnsMany("CustomerManagement.Domain.Aggregates.CustomerAggregate.Telephone", "Telephones", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Extension")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("nvarchar(8)");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)");

                            b1.Property<int>("TelephoneTypeId")
                                .HasColumnType("int")
                                .HasColumnName("TelephoneTypeId");

                            b1.HasKey("CustomerId", "Id");

                            b1.HasIndex("TelephoneTypeId");

                            b1.ToTable("Telephone");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");

                            b1.HasOne("CustomerManagement.Domain.Aggregates.CustomerAggregate.TelephoneType", "TelephoneType")
                                .WithMany()
                                .HasForeignKey("TelephoneTypeId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.Navigation("TelephoneType");
                        });

                    b.Navigation("Addresses");

                    b.Navigation("Gender");

                    b.Navigation("Telephones");
                });

            modelBuilder.Entity("CustomerManagement.Domain.Aggregates.CustomerAggregate.Gender", b =>
                {
                    b.Navigation("Customers");
                });
#pragma warning restore 612, 618
        }
    }
}
